# Generated by Django 2.2.6 on 2019-10-26 11:33

from django.db import migrations, models
import django.db.models.deletion
import netfields.fields
import sipam.utilities.enums
import sipam.utilities.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('label', models.CharField(default='VMs', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CIDR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('cidr', netfields.fields.CidrAddressField(max_length=43, unique=True)),
                ('fqdn', sipam.utilities.fields.FQDNField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prefixes', to='sipam.Pool')),
                ('flag', models.CharField(choices=[(sipam.utilities.enums.FlagChoices('reservation'), 'reservation'), (sipam.utilities.enums.FlagChoices('assignment'), 'assignment'), (sipam.utilities.enums.FlagChoices('host'), 'host')], default=sipam.utilities.enums.FlagChoices('reservation'), max_length=11)),
            ],
            options={
                'ordering': ('cidr',),
            },
        ),
    ]
