# Generated by Django 2.2.6 on 2019-10-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipam', '0001_sipam_basic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='label',
            field=models.CharField(max_length=100),
        ),
    ]
