# Generated by Django 2.2 on 2019-04-09 21:42

from django.db import migrations
import sipam.utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sipam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='subdomain',
            field=sipam.utilities.fields.URLField(blank=True, null=True),
        ),
    ]
