# Generated by Django 2.2.6 on 2019-11-03 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sipam', '0002_auto_20191026_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cidr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='sipam.CIDR')),
                ('edited', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('name', 'cidr'), name='name-cidr'),
        ),
    ]
