# Generated by Django 2.2 on 2019-04-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sipam', '0002_auto_20190409_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IP',
        ),
    ]
