# Generated by Django 2.2.6 on 2019-10-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipam', '0002_auto_20191026_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='cidr',
            name='tags',
            field=models.ManyToManyField(to='sipam.Tag'),
        ),
    ]
