# Generated by Django 2.2 on 2019-04-18 00:11

from django.db import migrations, models
import django.db.models.deletion
import netfields.fields
import sipam.utilities.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sipam', '0003_delete_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIDR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('cidr', netfields.fields.CidrAddressField(max_length=43)),
                ('fqdn', sipam.utilities.fields.FQDNField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pool', models.ForeignKey(blank=True, null=True,
                                           on_delete=django.db.models.deletion.DO_NOTHING, related_name='prefixes', to='sipam.Pool')),
            ],
            options={
                'ordering': ('cidr',),
            },
        ),
        migrations.DeleteModel(
            name='Prefix',
        ),
    ]
