# Generated by Django 2.2.1 on 2019-05-03 19:47

from django.db import migrations, models
import sipam.utilities.enums


class Migration(migrations.Migration):

    dependencies = [
        ('sipam', '0006_cidr_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidr',
            name='flag',
            field=models.CharField(choices=[(sipam.utilities.enums.FlagChoices('reservation'), 'reservation'), (sipam.utilities.enums.FlagChoices(
                'assignment'), 'assignment'), (sipam.utilities.enums.FlagChoices('host'), 'host')], default=sipam.utilities.enums.FlagChoices('reservation'), max_length=11),
        ),
    ]
