{{- if .Values.backend.djangoSecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: backend
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ include "sipam.secrets.django.secret.name" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "sipam.secrets.django.secret.key" . }}: {{ include "common.secrets.passwords.manage" (dict "secret" ( include "sipam.secrets.django.secret.name" . ) "key" ( include "sipam.secrets.django.secret.key" . ) "providedValues" (list .Values.backend.config.django.secret .Values.backend.djangoSecret.value) "length" 64 "strong" true "context" $) }}
{{- end }}
{{- if .Values.backend.dbSecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: backend
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ include "sipam.secrets.db.secret.name" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "sipam.secrets.db.secret.key" . }}: {{ include "common.secrets.passwords.manage" (dict "secret" ( include "sipam.secrets.db.secret.name" . ) "key" ( include "sipam.secrets.db.secret.key" . ) "providedValues" (list .Values.backend.config.db.password .Values.backend.dbSecret.value) "length" 1 "strong" false "context" $) }}
{{- end }}
