image: python:3.9-bullseye

variables:
  POSTGRES_USER: sipam
  POSTGRES_PASSWORD: sipam
  POSTGRES_DB: sipam
  prometheus_multiproc_dir: /tmp
  npm_prefix: frontend/sipam/
  KUBECONFORM_VERSION: "0.4.8"

stages:
  - test
  - build
  - build_containers

eslint:
  image: node:lts-bullseye
  stage: test
  before_script:
    - yarn --cwd ${npm_prefix} install
  script:
    - yarn --cwd ${npm_prefix} lint

yarn_build:
  image: node:lts-bullseye
  stage: build
  before_script:
    - yarn --cwd ${npm_prefix} install
  script:
    - yarn --cwd ${npm_prefix} build
  artifacts:
    paths:
      - frontend/sipam/dist
  needs: []

helm_build:
  image: docker.io/dtzar/helm-kubectl:3.5.0
  stage: build
  before_script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo add selfnet "${NEXUS_URL}/repository/selfnet-helm/" --username "${NEXUS_USERNAME}" --password "${NEXUS_PASSWORD}"
  script:
    - helm dependency build deploy/helm/sipam
    - helm package deploy/helm/sipam
    - curl -T *.tgz -v -u "${NEXUS_USERNAME}:${NEXUS_PASSWORD}" "${NEXUS_URL}/repository/selfnet-helm/"
  needs:
    - helm_lint
  only:
    - tags

helm_lint:
  image: docker.io/dtzar/helm-kubectl:3.5.0
  stage: test
  before_script:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - wget "https://github.com/yannh/kubeconform/releases/download/v${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz"
    - tar xzvf kubeconform-linux-amd64.tar.gz kubeconform
    - mv kubeconform /kubeconform
    - chmod +x /kubeconform
  script:
    - |
      bash -c "! grep -r -I -n '[[:blank:]]$' deploy/"
    - helm dependency build deploy/helm/sipam
    - helm lint deploy/helm/sipam
    - helm template sipam deploy/helm/sipam | /kubeconform -ignore-missing-schemas -summary

flake8:
  stage: test
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry --version
    - poetry run flake8 .

pytest:
  services:
    - postgres:latest
  stage: test
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry run coverage run -m pytest
    - poetry run coverage report

backend_container:
  image: quay.io/containers/buildah:latest
  stage: build_containers
  before_script:
    - export STORAGE_DRIVER=vfs
    - export BUILDAH_FORMAT=docker
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah bud -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA -f docker/Dockerfile.backend .
    - buildah push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
    - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then buildah tag $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/backend:latest; fi
    - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then buildah push $CI_REGISTRY_IMAGE/backend:latest; fi
  needs:
    - flake8
    - pytest
  only:
    - branches

frontend_container:
  image: quay.io/containers/buildah:latest
  stage: build_containers
  before_script:
    - export STORAGE_DRIVER=vfs
    - export BUILDAH_FORMAT=docker
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah bud -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA -f docker/Dockerfile.frontend .
    - buildah push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
    - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then buildah tag $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/frontend:latest; fi
    - if [ "$CI_COMMIT_REF_NAME" == "main" ]; then buildah push $CI_REGISTRY_IMAGE/frontend:latest; fi
  needs:
    - yarn_build
    - eslint
  only:
    - branches

backend_container_release:
  image: quay.io/containers/buildah:latest
  stage: build_containers
  before_script:
    - export STORAGE_DRIVER=vfs
    - export BUILDAH_FORMAT=docker
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah bud -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME -f docker/Dockerfile.backend .
    - buildah push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHORT_SHA
    - buildah push $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_NAME
  needs:
    - flake8
    - pytest
  only:
    - tags

frontend_container_release:
  image: quay.io/containers/buildah:latest
  stage: build_containers
  before_script:
    - export STORAGE_DRIVER=vfs
    - export BUILDAH_FORMAT=docker
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah bud -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME -f docker/Dockerfile.frontend .
    - buildah push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHORT_SHA
    - buildah push $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_NAME
  needs:
    - yarn_build
    - eslint
  only:
    - tags
