image: python:3.8-buster

variables:
  POSTGRES_USER: sipam
  POSTGRES_PASSWORD: sipam
  POSTGRES_DB: sipam
  prometheus_multiproc_dir: /tmp
  npm_prefix: frontend/sipam/

stages:
  - test
  - build

eslint:
  image: node:15.3.0-buster
  stage: test
  before_script:
    - npm i --prefix ${npm_prefix} -g eslint
  script:
    - eslint ${npm_prefix}

# npm-build:
#   image: node:15.3.0-buster
#   stage: build
#   before_script:
#     - npm ci --prefix ${npm_prefix}
#   script:
#     - npm run --prefix ${npm_prefix} build


flake8:
  stage: test
  before_script:
    - pip install pipenv
  script:
    - pipenv install --dev
    - pipenv --version
    - pipenv run flake8 .

security:
  stage: test
  variables:
    PIPENV_PYUP_API_KEY: ""
  before_script:
    - pip install pipenv
  script:
    - pipenv check

pytest:
  services:
    - postgres:latest
  stage: test
  before_script:
    - pip install pipenv
  script:
    - pipenv install --dev
    - pipenv run coverage run -m pytest
    - pipenv run coverage report

include:
  - template: Code-Quality.gitlab-ci.yml
