image: python:3.8-buster

variables:
  POSTGRES_USER: sipam
  POSTGRES_PASSWORD: sipam
  POSTGRES_DB: sipam
  prometheus_multiproc_dir: /tmp
  npm_prefix: frontend/sipam/

stages:
  - test
  - build

eslint:
  image: node:lts-buster
  stage: test
  before_script:
    - yarn --cwd ${npm_prefix} install
  script:
    - yarn --cwd ${npm_prefix} lint

# npm-build:
#   image: node:lts-buster
#   stage: build
#   script:
#     - yarn --cwd ${npm_prefix} build
#   needs:
#     - eslint


flake8:
  stage: test
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry --version
    - poetry run flake8 .

pytest:
  services:
    - postgres:latest
  stage: test
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry run coverage run -m pytest
    - poetry run coverage report

include:
  - template: Code-Quality.gitlab-ci.yml
