version: "3"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME:?err}
      POSTGRES_USER: ${DATABASE_USER:?err}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?err}
      PGDATA: /data/db
    volumes:
      - ./data/db:/data/db:z
    restart: unless-stopped

  frontend:
    image: node:16-alpine
    entrypoint: sh -c 'if [ ! -d "node_modules" ]; then yarn install; fi && yarn serve'
    environment:
      OIDC_ENDPOINT: ${OIDC_ENDPOINT:-https://sap.selfnet.de/auth/realms/master}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-sipam-dev}
      OIDC_AUTO_SIGNIN: ${OIDC_AUTO_SIGNIN:-true}
      API_URL: ${API_URL:-http://localhost:8000/api/v1}
      APP_URL: ${APP_URL:-http://localhost:8181}
      DEBUG: true
    volumes:
      - ./frontend:/app:z
    working_dir: /app
    restart: unless-stopped
    ports:
      - 8181:8181
    depends_on:
      - backend

  backend:
    build:
      # TODO: image does not provide hot reloading
      context: backend
      dockerfile: Containerfile.dev
    command: ["runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app:z
    working_dir: /app
    environment:
      SIPAM_DATABASE_HOST: ${DATABASE_HOST:-postgres}
      SIPAM_DATABASE_NAME: ${DATABASE_NAME:?err}
      SIPAM_DATABASE_USER_NAME: ${DATABASE_USER:?err}
      SIPAM_DATABASE_USER_PASSWORD: ${DATABASE_PASSWORD:?err}
      SIPAM_OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-sipam-dev}
      SIPAM_OIDC_ENDPOINT: ${OIDC_ENDPOINT:-https://sap.selfnet.de/auth/realms/master}
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:?err}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:?err}
    ports:
      - ${PGADMIN_PORT:-5050}:80
    restart: unless-stopped
    depends_on:
      - postgres
