version: "3"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-sipam}
      POSTGRES_USER: ${DATABASE_USER:?err}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?err}
      PGDATA: /data/postgres
    volumes:
      - ${DATA_DIR:-./data}/postgres:/data/postgres:z
    restart: unless-stopped

  frontend:
    image: node:18-alpine
    entrypoint: sh -c 'if [ ! -d "node_modules" ]; then yarn install; fi && yarn dev --host'
    environment:
      VITE_OIDC_ENDPOINT: ${OIDC_ENDPOINT:-https://sap.selfnet.de/auth/realms/master}
      VITE_OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-sipam-dev}
      VITE_OIDC_AUTO_SIGNIN: true
      VITE_API_URL: ${API_URL:-http://localhost:${BACKEND_PORT:-8000}/api/v1}
      VITE_APP_URL: ${APP_URL:-http://localhost:${FRONTEND_PORT:-3000}}
      VITE_DEBUG: true
    volumes:
      - ./frontend:/app:z
    working_dir: /app
    restart: unless-stopped
    ports:
      - ${FRONTEND_PORT:-3000}:3000
    depends_on:
      - backend

  backend:
    build:
      # TODO: image does only provide semi-hot-reloading
      context: backend
      dockerfile: Containerfile.dev
    command: ["runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/app:z
    working_dir: /app
    environment:
      SIPAM_DATABASE_HOST: ${DATABASE_HOST:-postgres}
      SIPAM_DATABASE_NAME: ${DATABASE_NAME:-sipam}
      SIPAM_DATABASE_USER_NAME: ${DATABASE_USER:?err}
      SIPAM_DATABASE_USER_PASSWORD: ${DATABASE_PASSWORD:?err}
      SIPAM_OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-sipam-dev}
      SIPAM_OIDC_ENDPOINT: ${OIDC_ENDPOINT:-https://sap.selfnet.de/auth/realms/master}
    ports:
      - ${BACKEND_PORT:-8000}:8000
    restart: unless-stopped
    depends_on:
      - postgres
