openapi: "3.0.0"
info:
  version: 1.0.0
  title: Selfnet IPAM
  license:
    name: MIT
servers:
  - url: http://sipam.selfnet.de/api/v1
paths:
  /subnets:
    get:
      summary: List all Subnets 
      operationId: listSubnets
      tags:
        - subnets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of subnets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Subnets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a Subnet
      operationId: createSubnet
      tags:
        - subnets
      responses:
        201:
          description: Subnet created and return it.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subnet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /subnets/{subnetId}:
    get:
      summary: Info for a specific Subnet
      operationId: getSubnet
      tags:
        - subnets
      parameters:
        - name: subnetId
          in: path
          required: true
          description: The subnet to get information for.
          schema:
            type: string
      responses:
        200:
          description: Return the Subnet requested.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Subnet"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pool:
      type: object
      required:
        - name
        - subnets
      properties:
        name:
          type: string
        subnets:
          type: array
          items:
            $ref: "#/components/schemas/Subnet"
        max_cidr:
          type: object
          properties:
            v6:
              type: integer
              format: int32
              minimum: 16
              maximum: 128
            v4:
              type: integer
              format: int32
              minimum: 8
              maximum: 32
    Pools:
      type: array
      items:
        $ref: "#/components/schemas/Pool"
    IP:
      type: object
      required:
        - ip
      properties:
        ip:
          type: string
          format: ip
        parent:
          $ref: "#/components/schemas/Subnet"
        fqdn:
          type: string
          format: fqdn
        description:
          type: string
        
        
    Subnet:
      type: object
      required:
        - ipnet
      properties:
        subnetId:
          type: string
          format: uuid
          readOnly: true
        ipnet:
          type: string
          format: ipnet
        parent:
          $ref: "#/components/schemas/Subnet"
        subdomain:
          type: string
          format: fqdn
        description:
          type: string
    Subnets:
      type: array
      items:
        $ref: "#/components/schemas/Subnet"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string