# Generated by Django 3.0.2 on 2020-01-24 23:21

from django.db import migrations, models

import sipam.utilities.enums


class Migration(migrations.Migration):
    dependencies = [
        ("sipam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="poolType",
            field=models.CharField(
                choices=[("Host Linknet", "Host Linknet"), ("VM Linknet", "VM Linknet"), ("Arbitrary", "Arbitrary")],
                default=sipam.utilities.enums.PoolType["ARBITRARY"],
                max_length=12,
            ),
        ),
    ]
