# Generated by Django 3.1.2 on 2020-10-14 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaggedtoken',
            name='created',
        ),
        migrations.RemoveField(
            model_name='flaggedtoken',
            name='key',
        ),
        migrations.RemoveField(
            model_name='flaggedtoken',
            name='user',
        ),
        migrations.AddField(
            model_name='flaggedtoken',
            name='token_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='authtoken.token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
