# Generated by Django 3.1.2 on 2020-10-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201014_2112'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flaggedtoken',
            table=None,
        ),
    ]
