# Generated by Django 3.1.3 on 2020-11-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
        ('accounts', '0003_auto_20201014_2113'),
    ]

    operations = [
    ]
