# Generated by Django 3.1.3 on 2020-11-23 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20201123_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedtoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
