FROM node:lts-buster AS build_frontend
WORKDIR /usr/src/app/
COPY frontend/sipam/ .
RUN yarn install && yarn build

FROM docker.io/nginxinc/nginx-unprivileged:stable-alpine
COPY --from=build_frontend /usr/src/app/dist /usr/share/nginx/html
