info:
  description: ''
  title: ''
  version: ''
openapi: 3.0.0
paths:
  /api/v1/cidr/:
    get:
      description: Get the Root Prefixes with their childrens
      operationId: cidr_list
      parameters:
      - in: query
        name: page
        schema:
          description: A page number within the paginated result set.
          title: Page
          type: integer
      tags:
      - cidr
    post:
      description: API endpoint that allows Prefixes to be viewed or edited.
      operationId: cidr_create
      tags:
      - cidr
  /api/v1/cidr/{id}/:
    delete:
      description: API endpoint that allows Prefixes to be viewed or edited.
      operationId: cidr_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this cidr.
          title: id
          type: string
      tags:
      - cidr
    get:
      description: API endpoint that allows Prefixes to be viewed or edited.
      operationId: cidr_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this cidr.
          title: id
          type: string
      tags:
      - cidr
    patch:
      description: API endpoint that allows Prefixes to be viewed or edited.
      operationId: cidr_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this cidr.
          title: id
          type: string
      tags:
      - cidr
    put:
      description: API endpoint that allows Prefixes to be viewed or edited.
      operationId: cidr_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this cidr.
          title: id
          type: string
      tags:
      - cidr
  /api/v1/cidr/{id}/ips/:
    get:
      description: API Endpoint that allows direct children ips to be viewed.
      operationId: cidr_ips
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this cidr.
          title: id
          type: string
      tags:
      - cidr
  /api/v1/cidr/{id}/subcidr/:
    get:
      description: API endpoint that allows direct subordinary cidr (networks) to
        be viewed.
      operationId: cidr_subcidr
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this cidr.
          title: id
          type: string
      tags:
      - cidr
  /api/v1/cidr/{id}/supercidr/:
    get:
      description: API endpoint that allows direct super cidr (network) to be viewed.
      operationId: cidr_supercidr
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A UUID string identifying this cidr.
          title: id
          type: string
      tags:
      - cidr
  /api/v1/pools/:
    get:
      description: List all pools
      operationId: pools_list
      parameters:
      - in: query
        name: page
        schema:
          description: A page number within the paginated result set.
          title: Page
          type: integer
      tags:
      - pools
    post:
      description: API endpoint that allows Pools to be viewed or edited.
      operationId: pools_create
      tags:
      - pools
  /api/v1/pools/{id}/:
    delete:
      description: API endpoint that allows Pools to be viewed or edited.
      operationId: pools_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique value identifying this pool.
          title: id
          type: string
      tags:
      - pools
    get:
      description: API endpoint that allows Pools to be viewed or edited.
      operationId: pools_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique value identifying this pool.
          title: id
          type: string
      tags:
      - pools
    patch:
      description: API endpoint that allows Pools to be viewed or edited.
      operationId: pools_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique value identifying this pool.
          title: id
          type: string
      tags:
      - pools
    put:
      description: API endpoint that allows Pools to be viewed or edited.
      operationId: pools_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique value identifying this pool.
          title: id
          type: string
      tags:
      - pools
servers:
- url: ''
